INSERT INTO pizza(name, price, description, photo)VALUES('Pizza Margherita', 6.00, 'Pomodoro, Mozzarella, Olio, Basilico', 'https://cookingitaly.de/wp-content/uploads/2020/02/DSC06476.jpg');
INSERT INTO pizza(name, price, description, photo)VALUES('Pizza Marinara', 5.00, 'Pomodoro, Origano, Aglio, Olio', 'https://hnmagazine.co.uk/wp-content/uploads/2021/02/image1.jpg');
INSERT INTO pizza(name, price, description, photo)VALUES('Pizza Ortolana', 8.00, 'Zucchine, Peperoni, Zucchine, Mozzarella, Olio', 'http://www.ristorantepizzeriapummaro.com/wp-content/uploads/2022/05/OrtolanaBig-1.jpg');
INSERT INTO pizza(name, price, description, photo)VALUES('Pizza Wrustel Patatine', 8.00, 'Patatine Fritte, Wrustel, Mozzarella, Olio', 'http://www.scattidigusto.it/wp-content/uploads/2015/11/pizza-wurstel-e-patatine.jpg');
INSERT INTO offerta_Speciale(titolo, data_fine, data_inizio, pizza_id)VALUES('Offerta Inverno', '2024-01-30', '2024-01-20', 1);
INSERT INTO db_pizzeria.ingredienti(name)VALUES('Mozzarella');
INSERT INTO db_pizzeria.ingredienti(name)VALUES('Salsiccia');
INSERT INTO db_pizzeria.ingredienti(name)VALUES('Mortadella');
INSERT INTO db_pizzeria.ingredienti(name)VALUES('Salame');
INSERT INTO db_pizzeria.ingredienti(name)VALUES('Funghi');
INSERT INTO db_pizzeria.ingredienti(name)VALUES('Prosciutto Crudo');
INSERT INTO db_pizzeria.ingredienti(name)VALUES('Provola');